In [1]:
using LinearAlgebra
using BenchmarkTools
using PyPlot
using FFTW

In [5]:
y = reshape([1:125...], 5,5,5)
x = zeros(Int64, 8,8,8)
x[1:5,1:5, 1:5] .= y

5×5×5 view(::Array{Int64, 3}, 1:5, 1:5, 1:5) with eltype Int64:
[:, :, 1] =
 1   6  11  16  21
 2   7  12  17  22
 3   8  13  18  23
 4   9  14  19  24
 5  10  15  20  25

[:, :, 2] =
 26  31  36  41  46
 27  32  37  42  47
 28  33  38  43  48
 29  34  39  44  49
 30  35  40  45  50

[:, :, 3] =
 51  56  61  66  71
 52  57  62  67  72
 53  58  63  68  73
 54  59  64  69  74
 55  60  65  70  75

[:, :, 4] =
 76  81  86  91   96
 77  82  87  92   97
 78  83  88  93   98
 79  84  89  94   99
 80  85  90  95  100

[:, :, 5] =
 101  106  111  116  121
 102  107  112  117  122
 103  108  113  118  123
 104  109  114  119  124
 105  110  115  120  125

In [34]:
a = ifft(fft(x).*2)
(a[5,:])

8-element Vector{ComplexF64}:
                    10.0 + 0.0im
                    20.0 + 0.0im
                    30.0 + 0.0im
                    40.0 + 0.0im
                    50.0 + 0.0im
                     0.0 + 0.0im
                     0.0 + 0.0im
 -1.7763568394002505e-15 + 0.0im

In [41]:
b = ifft(fft(y).*2)

5×5×5 Array{ComplexF64, 3}:
[:, :, 1] =
  2.0+0.0im  12.0+0.0im  22.0+0.0im  32.0+0.0im  42.0+0.0im
  4.0+0.0im  14.0+0.0im  24.0+0.0im  34.0+0.0im  44.0+0.0im
  6.0+0.0im  16.0+0.0im  26.0+0.0im  36.0+0.0im  46.0+0.0im
  8.0+0.0im  18.0+0.0im  28.0+0.0im  38.0+0.0im  48.0+0.0im
 10.0+0.0im  20.0+0.0im  30.0+0.0im  40.0+0.0im  50.0+0.0im

[:, :, 2] =
 52.0+0.0im  62.0+0.0im  72.0+0.0im  82.0+0.0im   92.0+0.0im
 54.0+0.0im  64.0+0.0im  74.0+0.0im  84.0+0.0im   94.0+0.0im
 56.0+0.0im  66.0+0.0im  76.0+0.0im  86.0+0.0im   96.0+0.0im
 58.0+0.0im  68.0+0.0im  78.0+0.0im  88.0+0.0im   98.0+0.0im
 60.0+0.0im  70.0+0.0im  80.0+0.0im  90.0+0.0im  100.0+0.0im

[:, :, 3] =
 102.0+0.0im  112.0+0.0im  122.0+0.0im  132.0+0.0im  142.0+0.0im
 104.0+0.0im  114.0+0.0im  124.0+0.0im  134.0+0.0im  144.0+0.0im
 106.0+0.0im  116.0+0.0im  126.0+0.0im  136.0+0.0im  146.0+0.0im
 108.0+0.0im  118.0+0.0im  128.0+0.0im  138.0+0.0im  148.0+0.0im
 110.0+0.0im  120.0+0.0im  130.0+0.0im  140.0+0.0im  150.0+0.0im

[:,

In [45]:
real.(ifft(fft(x)))

8×8×8 Array{Float64, 3}:
[:, :, 1] =
  1.0           6.0          11.0          …  -3.10862e-15   0.0
  2.0           7.0          12.0              3.55271e-15   3.9968e-15
  3.0           8.0          13.0              8.43769e-15   1.02141e-14
  4.0           9.0          14.0              2.66454e-15   0.0
  5.0          10.0          15.0             -2.66454e-15   8.88178e-16
 -5.75928e-15  -3.88179e-15  -5.93969e-15  …  -7.60503e-15  -7.89505e-15
 -3.55271e-15   1.93241e-15   1.22125e-15     -6.55032e-15  -5.13301e-15
 -6.28664e-15  -4.37917e-15  -6.55032e-15     -6.32827e-15  -7.43691e-15

[:, :, 2] =
 26.0          31.0          36.0          …  -5.51843e-16   2.06264e-16
 27.0          32.0          37.0             -2.09962e-15  -6.09642e-15
 28.0          33.0          38.0              5.36063e-15   6.50354e-16
 29.0          34.0          39.0              1.61473e-15  -1.0515e-14
 30.0          35.0          40.0              1.51622e-15   2.06264e-16
 -5.41975e-15  -9.9

In [46]:
real.(fft3d(fft3d(x, 1), -1))

8×8×8 Array{Float64, 3}:
[:, :, 1] =
  1.0           6.0          11.0          …  -6.66134e-15  -1.77636e-15
  2.0           7.0          12.0              3.9968e-15    3.55271e-15
  3.0           8.0          13.0             -4.88498e-15   3.55271e-15
  4.0           9.0          14.0              7.10543e-15   1.77636e-15
  5.0          10.0          15.0             -6.21725e-15  -2.66454e-15
 -3.37924e-15  -4.91516e-16   1.27676e-15  …  -6.60583e-15  -5.70534e-15
 -2.07473e-15   8.82519e-17   4.94049e-15     -8.71525e-15  -9.12454e-15
 -1.4086e-15   -1.27752e-15   1.08247e-15     -8.52096e-15  -8.30368e-15

[:, :, 2] =
 26.0          31.0          36.0          …   1.30071e-16   9.37434e-16
 27.0          32.0          37.0              2.79923e-15  -5.83628e-15
 28.0          33.0          38.0             -5.51843e-16   1.2022e-15
 29.0          34.0          39.0              9.92697e-15   1.34996e-15
 30.0          35.0          40.0             -3.50808e-15   6.01098e-16
 -

In [7]:
fft3d(x, 1)

8×8×8 Array{ComplexF64, 3}:
[:, :, 1] =
 1.0+0.0im   6.0+0.0im  11.0+0.0im  …  1.0+0.0im   6.0+0.0im  11.0+0.0im
 2.0+0.0im   7.0+0.0im  12.0+0.0im     2.0+0.0im   7.0+0.0im  12.0+0.0im
 3.0+0.0im   8.0+0.0im  13.0+0.0im     3.0+0.0im   8.0+0.0im  13.0+0.0im
 4.0+0.0im   9.0+0.0im  14.0+0.0im     4.0+0.0im   9.0+0.0im  14.0+0.0im
 5.0+0.0im  10.0+0.0im  15.0+0.0im     5.0+0.0im  10.0+0.0im  15.0+0.0im
 1.0+0.0im   6.0+0.0im  11.0+0.0im  …  1.0+0.0im   6.0+0.0im  11.0+0.0im
 2.0+0.0im   7.0+0.0im  12.0+0.0im     2.0+0.0im   7.0+0.0im  12.0+0.0im
 3.0+0.0im   8.0+0.0im  13.0+0.0im     3.0+0.0im   8.0+0.0im  13.0+0.0im

[:, :, 2] =
 26.0+0.0im  31.0+0.0im  36.0+0.0im  …  26.0+0.0im  31.0+0.0im  36.0+0.0im
 27.0+0.0im  32.0+0.0im  37.0+0.0im     27.0+0.0im  32.0+0.0im  37.0+0.0im
 28.0+0.0im  33.0+0.0im  38.0+0.0im     28.0+0.0im  33.0+0.0im  38.0+0.0im
 29.0+0.0im  34.0+0.0im  39.0+0.0im     29.0+0.0im  34.0+0.0im  39.0+0.0im
 30.0+0.0im  35.0+0.0im  40.0+0.0im     30.0+0.0im  35.0+0.0im 

In [6]:
function bit_reversal_permutation!(x, dim)
    N = size(x, dim)
    j = 1
    @inbounds for i in 1:N
        if j > i
            if dim == 1
                temp       = x[i, :, :]
                x[i, :, :] = x[j, :, :]
                x[j, :, :] = temp
            elseif dim == 2
                temp       = x[:, i, :]
                x[:, i, :] = x[:, j, :]
                x[:, j, :] = temp
            elseif dim == 3
                temp       = x[:, :, i]
                x[:, :, i] = x[:, :, j]
                x[:, :, j] = temp
            end
        end
        m = N >> 1
        while m >= 1 && j > m
            j -= m
            m >>= 1
        end
        j += m
    end
end

function fft1d_dim!(x, dim, isign)
    
    N = size(x, dim)

    step = 2
    while step <= N
        half_step = step ÷ 2
        w_m = exp(-2im* isign * π / step)

        if dim == 1
            @inbounds for k in 1:step:N, l in 1:size(x, 2), m in 1:size(x, 3)
                w = 1.0
                @inbounds for n in 0:(half_step-1)
                    u = x[k + n, l, m]
                    t = w * x[k + n + half_step, l, m]
                    x[k + n, l, m] = u + t
                    x[k + n + half_step, l, m] = u - t
                    w *= w_m
                end
            end
        elseif dim == 2
            @inbounds for k in 1:size(x, 1), l in 1:step:N, m in 1:size(x, 3)
                w = 1.0
                @inbounds for n in 0:(half_step-1)
                    u = x[k, l + n, m]
                    t = w * x[k, l + n + half_step, m]
                    x[k, l + n, m] = u + t
                    x[k, l + n + half_step, m] = u - t
                    w *= w_m
                end
            end
        elseif dim == 3
            @inbounds for k in 1:size(x, 1), l in 1:size(x, 2), m in 1:step:N
                w = 1.0
                @inbounds for n in 0:(half_step-1)
                    u = x[k, l, m + n]
                    t = w * x[k, l, m + n + half_step]
                    x[k, l, m + n] = u + t
                    x[k, l, m + n + half_step] = u - t
                    w *= w_m
                end
            end
        end

        step *= 2
    end

    if isign == -1
        x .= x ./ N
    end
    
    return x
end

function fft3d(x, isign) #zrobić żeby w tablicy po kolei były przechowywane real i im
    ρfft = zeros(ComplexF64, 8,8,8)
    ρfft[1:size(x, 1), 1:size(x, 2), 1:size(x, 3)] .= convert(Array{ComplexF64, 3}, x)
    for i in 6:8, j in 1:5, k in 1:5
        ρfft[i,j,k] = convert(ComplexF64, ρfft[mod(i, 5),j,k])
    end
    for i in 1:8, j in 6:8, k in 1:5
        ρfft[i,j,k] = convert(ComplexF64, ρfft[i,mod(j, 5),k])
    end
    for i in 1:8, j in 1:8, k in 6:8
        ρfft[i,j,k] = convert(ComplexF64, ρfft[i,j,mod(k, 5) ])
    end
    # println(size(ρfft))
    ρfft
    # println(ρfft)

    # for dim in 1:3
    #     bit_reversal_permutation!(ρfft, dim)
    #     #println(ρfft, "\n")
    #     fft1d_dim!(ρfft, dim, isign)
    # end
    # return ρfft
end

fft3d (generic function with 1 method)

In [64]:
function cooley_tukey(x)
    N = length(x)

    if (N > 2)
        x_odd = cooley_tukey(x[1:2:N])
        x_even = cooley_tukey(x[2:2:N])
    else
        x_odd = x[1]
        x_even = x[2]
    end
    n = 0:length(x_odd)-1
    half = div(N,2)
    println(n)
    factor = exp.(-2im*pi*n/N)
    println(factor)
    println( vcat(x_odd .+ x_even .* factor[1:half],
                x_odd .- x_even .* factor[1:half]))
    return vcat(x_odd .+ x_even .* factor[1:half],
                x_odd .- x_even .* factor[1:half])

end

cooley_tukey (generic function with 1 method)

In [65]:
cooley_tukey([1:8...])

0:0
ComplexF64[1.0 - 0.0im]
ComplexF64[6.0 - 0.0im, -4.0 + 0.0im]
0:0
ComplexF64[1.0 - 0.0im]
ComplexF64[10.0 - 0.0im, -4.0 + 0.0im]
0:1
ComplexF64[1.0 - 0.0im, 6.123233995736766e-17 - 1.0im]
ComplexF64[16.0 - 0.0im, -4.0 + 4.0im, -4.0 + 0.0im, -3.9999999999999996 - 4.0im]
0:0
ComplexF64[1.0 - 0.0im]
ComplexF64[8.0 - 0.0im, -4.0 + 0.0im]
0:0
ComplexF64[1.0 - 0.0im]
ComplexF64[12.0 - 0.0im, -4.0 + 0.0im]
0:1
ComplexF64[1.0 - 0.0im, 6.123233995736766e-17 - 1.0im]
ComplexF64[20.0 - 0.0im, -4.0 + 4.0im, -4.0 + 0.0im, -3.9999999999999996 - 4.0im]
0:3
ComplexF64[1.0 - 0.0im, 0.7071067811865476 - 0.7071067811865475im, 6.123233995736766e-17 - 1.0im, -0.7071067811865475 - 0.7071067811865476im]
ComplexF64[36.0 - 0.0im, -4.0 + 9.65685424949238im, -4.0 + 4.0im, -4.0 + 1.6568542494923797im, -4.0 + 0.0im, -3.9999999999999996 - 1.6568542494923797im, -3.9999999999999996 - 4.0im, -3.9999999999999987 - 9.65685424949238im]


8-element Vector{ComplexF64}:
                36.0 - 0.0im
                -4.0 + 9.65685424949238im
                -4.0 + 4.0im
                -4.0 + 1.6568542494923797im
                -4.0 + 0.0im
 -3.9999999999999996 - 1.6568542494923797im
 -3.9999999999999996 - 4.0im
 -3.9999999999999987 - 9.65685424949238im

In [9]:
cooley_tukey(x)

  2.745 ms (16368 allocations: 1.41 MiB)


1024-element Vector{ComplexF64}:
   513.8909618317466 - 0.0im
   5.761886723876073 + 3.4270554651149783im
  1.5693308225555063 + 5.379970864297059im
  -5.590677421672849 - 3.6441369650192676im
   5.771590179110686 - 8.916034114648337im
    8.06425919108073 - 8.642533499054089im
   1.753568893150483 + 21.54031665861823im
   6.070425148858878 - 8.932239373030464im
 0.22171019654952856 - 3.4142620880842864im
 -10.656919293429123 - 9.821826582312426im
  0.7131246272447607 + 6.636009638382709im
  -3.783540154381813 - 3.138217968366283im
 -2.9117044909899636 - 6.5965407360321064im
                     ⋮
 -2.9117044909899636 + 6.596540736032105im
  -3.783540154381818 + 3.1382179683662805im
  0.7131246272447656 - 6.636009638382711im
 -10.656919293429134 + 9.82182658231242im
 0.22171019654952373 + 3.4142620880842838im
   6.070425148858873 + 8.932239373030468im
  1.7535688931504891 - 21.54031665861823im
   8.064259191080723 + 8.642533499054096im
    5.77159017911068 + 8.916034114648342im
  -5.59

In [18]:
function fft1d(x, isign)
    N = length(x)

    # swap elements in array
    j = 1
    for i = 1:N
        if j > i
            temp = x[i]
            x[i] = x[j]
            x[j] = temp
        end
        m = N >> 1
        while m >= 1 && j > m
            j -= m
            m >>= 1
        end
        j += m
    end

    step = 2
    while step <= N
        half_step = step ÷ 2
        w_m = exp(-2im* isign * π / step)

        for k in 1:step:N
            w = 1.0
            for m in 0:(half_step-1)
                u = x[k + m]
                t = w * x[k + m + half_step]
                x[k + m] = u + t
                x[k + m + half_step] = u - t
                w *= w_m
            end
        end
        step *= 2
    end

    if isign == -1
        for i in 1:N
            x[i] /= N
        end
    end
    
    return x
end

fft1d (generic function with 1 method)

In [22]:
x = convert(Array{ComplexF64, 1}, [1:8...])
fft1d(fft1d(x, 1), -1)

8-element Vector{ComplexF64}:
                1.0 + 0.0im
 2.0000000000000004 - 2.718345674301793e-16im
                3.0 + 4.440892098500626e-16im
                4.0 + 3.8285686989269494e-16im
                5.0 + 0.0im
                6.0 - 4.978996250514798e-17im
                7.0 - 4.440892098500626e-16im
                8.0 - 6.123233995736767e-17im

In [23]:
x = convert(Array{ComplexF64, 1}, [1:8...])
ifft(fft(x))

8-element Vector{ComplexF64}:
 1.0 + 0.0im
 2.0 + 0.0im
 3.0 + 0.0im
 4.0 + 0.0im
 5.0 + 0.0im
 6.0 + 0.0im
 7.0 + 0.0im
 8.0 + 0.0im

In [57]:
function bit_reversal_permutation!(x, dim)
    N = size(x, dim)
    j = 1
    for i in 1:N
        if j > i
            if dim == 1
                temp       = x[i, :, :]
                x[i, :, :] = x[j, :, :]
                x[j, :, :] = temp
            elseif dim == 2
                temp       = x[:, i, :]
                x[:, i, :] = x[:, j, :]
                x[:, j, :] = temp
            elseif dim == 3
                temp       = x[:, :, i]
                x[:, :, i] = x[:, :, j]
                x[:, :, j] = temp
            end
        end
        m = N >> 1
        while m >= 1 && j > m
            j -= m
            m >>= 1
        end
        j += m
    end
end

function fft1d_dim!(x, dim, isign)
    N = size(x, dim)

    step = 2
    while step <= N
        half_step = step ÷ 2
        w_m = exp(-2im* isign * π / step)

        if dim == 1
            for k in 1:step:N, l in 1:size(x, 2), m in 1:size(x, 3)
                w = 1.0
                for n in 0:(half_step-1)
                    u = x[k + n, l, m]
                    t = w * x[k + n + half_step, l, m]
                    x[k + n, l, m] = u + t
                    x[k + n + half_step, l, m] = u - t
                    w *= w_m
                end
            end
        elseif dim == 2
            for k in 1:size(x, 1), l in 1:step:N, m in 1:size(x, 3)
                w = 1.0
                for n in 0:(half_step-1)
                    u = x[k, l + n, m]
                    t = w * x[k, l + n + half_step, m]
                    x[k, l + n, m] = u + t
                    x[k, l + n + half_step, m] = u - t
                    w *= w_m
                end
            end
        elseif dim == 3
            for k in 1:size(x, 1), l in 1:size(x, 2), m in 1:step:N
                w = 1.0
                for n in 0:(half_step-1)
                    u = x[k, l, m + n]
                    t = w * x[k, l, m + n + half_step]
                    x[k, l, m + n] = u + t
                    x[k, l, m + n + half_step] = u - t
                    w *= w_m
                end
            end
        end

        step *= 2
    end

    if isign == -1
        x .= x ./ N
    end
    
    return x
end

function fft3d(x, isign)
    for dim in 1:3
        bit_reversal_permutation!(x, dim)
        fft1d_dim!(x, dim, isign)
    end
    return x
end

fft3d (generic function with 1 method)

In [222]:
nx = 16
x = convert(Array{ComplexF64, 3}, rand(nx,nx,nx));
temp = similar(x)
temp .= x;

In [223]:
fft(x)

16×16×16 Array{ComplexF64, 3}:
[:, :, 1] =
    2047.2+0.0im       16.0887+10.1869im   …   16.0887-10.1869im
   24.3233+21.7546im   -7.2425+16.4597im      -7.52384-0.257674im
 -0.655054-1.42161im   -15.952+37.9304im      -9.31828+6.05375im
  -3.85718+5.08988im  -12.1058-8.67421im       25.2519+1.9285im
   1.53521-8.66543im   13.8437-1.46624im       1.08306-14.2283im
  -5.34719+2.01609im   22.0902+12.0757im   …  -13.5612-21.502im
  0.518549-4.30632im   1.68197+3.51058im      -22.1339+13.5552im
  -1.38445+20.5723im   8.59831+13.6736im       5.32042+3.8039im
   7.98016+0.0im      -2.51477-6.12254im      -2.51477+6.12254im
  -1.38445-20.5723im   5.32042-3.8039im        8.59831-13.6736im
  0.518549+4.30632im  -22.1339-13.5552im   …   1.68197-3.51058im
  -5.34719-2.01609im  -13.5612+21.502im        22.0902-12.0757im
   1.53521+8.66543im   1.08306+14.2283im       13.8437+1.46624im
  -3.85718-5.08988im   25.2519-1.9285im       -12.1058+8.67421im
 -0.655054+1.42161im  -9.31828-6.05375im       -1

In [224]:
fft3d(x, 1)

16×16×16 Array{ComplexF64, 3}:
[:, :, 1] =
    2047.2+0.0im       16.0887+10.1869im   …   16.0887-10.1869im
   24.3233+21.7546im   -7.2425+16.4597im      -7.52384-0.257674im
 -0.655054-1.42161im   -15.952+37.9304im      -9.31828+6.05375im
  -3.85718+5.08988im  -12.1058-8.67421im       25.2519+1.9285im
   1.53521-8.66543im   13.8437-1.46624im       1.08306-14.2283im
  -5.34719+2.01609im   22.0902+12.0757im   …  -13.5612-21.502im
  0.518549-4.30632im   1.68197+3.51058im      -22.1339+13.5552im
  -1.38445+20.5723im   8.59831+13.6736im       5.32042+3.8039im
   7.98016+0.0im      -2.51477-6.12254im      -2.51477+6.12254im
  -1.38445-20.5723im   5.32042-3.8039im        8.59831-13.6736im
  0.518549+4.30632im  -22.1339-13.5552im   …   1.68197-3.51058im
  -5.34719-2.01609im  -13.5612+21.502im        22.0902-12.0757im
   1.53521+8.66543im   1.08306+14.2283im       13.8437+1.46624im
  -3.85718-5.08988im   25.2519-1.9285im       -12.1058+8.67421im
 -0.655054+1.42161im  -9.31828-6.05375im       -1