In [1]:
using Random
using FFTW
using LinearAlgebra

In [41]:
Random.seed!(10)
LX = 1.0
LY = 1.0
LZ = 1.0
N = 5
epsilon_0 = 8.854e-12
x = [range(0, stop=LX, length=N);]
y = [range(0, stop=LY, length=N);]
z = [range(0, stop=LZ, length=N);]
ρ = rand(Float64, N,N,N)
;

In [42]:
x

5-element Vector{Float64}:
 0.0
 0.25
 0.5
 0.75
 1.0

In [39]:
n = 4
fs = 1
[0:n÷2-1; -n÷2:-1]  * fs/n

4-element Vector{Float64}:
  0.0
  0.25
 -0.5
 -0.25

In [40]:
n = 5
fs = 2
[0:(n-1)÷2; -(n-1)÷2:-1]  * fs/n

5-element Vector{Float64}:
  0.0
  0.4
  0.8
 -0.8
 -0.4

In [38]:
# Robimy DFT dla współrzędnych
xk = x .* 2π
yk = y .* 2π
zk = z .* 2π

5-element Vector{Float64}:
 0.0
 0.7853981633974483
 1.5707963267948966
 2.356194490192345
 3.141592653589793

In [ ]:
# Robimy DFT dla gęstości ładunków


In [ ]:
# rozwiązujemy w FFT
ϕ_hat = similar(ρ_hat)
for i in 1:size(ϕ_hat, 1), j in 1:size(ϕ_hat, 2), k in 1:size(ϕ_hat, 3)
    k2 = KX[i, 1, 1]^2 + KY[1, j, 1]^2 + KZ[1, 1, k]^2
    if k_sq != 0
        ϕ_hat[i, j, k] = ρ_hat[i, j, k] / (epsilon_0 * k2)
    else
        ϕ_hat[i, j, k] = 0
    end
end

In [ ]:
# odwracamy DFT -> IDFT

In [21]:
using FFTW
using LinearAlgebra

# Parametry siatki
N = 128  # Liczba punktów siatki w każdym wymiarze
L = 1.0  # Rozmiar domeny
h = L / N  # Krok siatki
epsilon_0 = 8.854e-12  # Przenikalność elektryczna próżni

# Siatka współrzędnych
x = range(0, stop=L, length=N)
y = range(0, stop=L, length=N)
z = range(0, stop=L, length=N)
X, Y, Z = [repeat(reshape(range, N, 1, 1), 1, N, N) for range in (x, y, z)]

# Gęstość ładunku ρ(x, y, z)
ρ = sin.(2π .* X) .* sin.(2π .* Y) .* sin.(2π .* Z)

# FFT gęstości ładunku
ρ_hat = rfft(ρ)

# Częstości przestrzenne
kx = fftfreq(N, 1/N) .* 2π
ky = fftfreq(N, 1/N) .* 2π
kz = fftfreq(N, 1/N) .* 2π
KX, KY, KZ = [repeat(reshape(freq, N, 1, 1), 1, N, N) for freq in (kx, ky, kz)]

# Rozwiązywanie równania Poissona w przestrzeni Fouriera
ϕ_hat = similar(ρ_hat)
for i in 1:size(ϕ_hat, 1), j in 1:N, k in 1:N
    k_sq = KX[i, 1, 1]^2 + KY[1, j, 1]^2 + KZ[1, 1, k]^2
    if k_sq != 0
        ϕ_hat[i, j, k] = ρ_hat[i, j, k] / (epsilon_0 * k_sq)
    else
        ϕ_hat[i, j, k] = 0
    end
end

# iFFT potencjału
ϕ = irfft(ϕ_hat, N)

# Teraz ϕ zawiera rozwiązanie równania Poissona
ϕ_real = real.(ϕ)  # Przejście na część rzeczywistą

128×128×128 Array{Float64, 3}:
[:, :, 1] =
  1.23702e16   1.23702e16   1.23702e16  …   1.23702e16   1.23702e16
  3.71106e16   3.71106e16   3.71106e16      3.71106e16   3.71106e16
  6.18507e16   6.18507e16   6.18507e16      6.18507e16   6.18507e16
  8.65887e16   8.65887e16   8.65887e16      8.65887e16   8.65887e16
  1.1132e17    1.1132e17    1.1132e17       1.1132e17    1.1132e17
  1.36038e17   1.36038e17   1.36038e17  …   1.36038e17   1.36038e17
  1.60727e17   1.60727e17   1.60727e17      1.60727e17   1.60727e17
  1.8537e17    1.8537e17    1.8537e17       1.8537e17    1.8537e17
  2.0994e17    2.0994e17    2.0994e17       2.0994e17    2.0994e17
  2.34403e17   2.34403e17   2.34403e17      2.34403e17   2.34403e17
  2.58717e17   2.58717e17   2.58717e17  …   2.58717e17   2.58717e17
  2.82833e17   2.82833e17   2.82833e17      2.82833e17   2.82833e17
  3.06691e17   3.06691e17   3.06691e17      3.06691e17   3.06691e17
  ⋮                                     ⋱               
 -2.82833e17  -2.82

In [28]:
Y

128×128×128 Array{Float64, 3}:
[:, :, 1] =
 0.0         0.0         0.0         …  0.0         0.0         0.0
 0.00787402  0.00787402  0.00787402     0.00787402  0.00787402  0.00787402
 0.015748    0.015748    0.015748       0.015748    0.015748    0.015748
 0.023622    0.023622    0.023622       0.023622    0.023622    0.023622
 0.0314961   0.0314961   0.0314961      0.0314961   0.0314961   0.0314961
 0.0393701   0.0393701   0.0393701   …  0.0393701   0.0393701   0.0393701
 0.0472441   0.0472441   0.0472441      0.0472441   0.0472441   0.0472441
 0.0551181   0.0551181   0.0551181      0.0551181   0.0551181   0.0551181
 0.0629921   0.0629921   0.0629921      0.0629921   0.0629921   0.0629921
 0.0708661   0.0708661   0.0708661      0.0708661   0.0708661   0.0708661
 0.0787402   0.0787402   0.0787402   …  0.0787402   0.0787402   0.0787402
 0.0866142   0.0866142   0.0866142      0.0866142   0.0866142   0.0866142
 0.0944882   0.0944882   0.0944882      0.0944882   0.0944882   0.0944882
 ⋮